### ISSUE TITLE
Authenticate to Argo with OAuth

### ISSUE THREAD

**Issue by gpelouze** [NaaVRE/NaaVRE-catalogue-service#19]
Requirements:
1. be able to authenticate to Argo workflows with SSO (use-case: in-cluster / NaaVRE-managed Argo)
2. be able to authenticate to Argo workflows without SSO (use-case: external Argo)

Solutions:
- Req. 1: connect to Argo on behalf of the user using their JWT.
  - Figure out the proper settings: how should the JWT be sent? what roles do the users need?  should extra configuration be set?
  - Apply Argo configuration
  - Send JWT to Argo with requests
- Req. 2: connect to Argo with a service account token (current behaviour)
- For both: decide on a VL configuration that allows to chose either JWT or SA token. For instance, use `access_token` if not `null`, else use the user's JWT:
  ```yaml
  {
    "vl_configurations": [
      {
        "name": "virtual_lab_1",
        "wf_engine_config": {
          "name": "argo",
          "api_endpoint": "https://example.naavre.net/argowf/api/v1",
          "access_token": null,
          "service_account": "executor",
          "workdir_storage_size": "1Gi"
        }
      },
      {
        "name": "virtual_lab_2",
        "wf_engine_config": {
          "name": "argo",
          "api_endpoint": "https://somewhere-else.example.net/argowf/api/v1",
          "access_token": "Bearer eyJh...",
          "service_account": "executor",
          "workdir_storage_size": "1Gi"
        }
      }
    ]
  }
  ```
